# FROM python:3.8

# # The enviroment variable ensures that the python output is set straight
# # to the terminal with out buffering it first
# ENV PYTHONUNBUFFERED 1

# WORKDIR /usr/src/app
# COPY backend/ ./
# RUN pip install -r requirements.txt
# EXPOSE 8000
# CMD ["python", "runserver"]