# Generated by Django 4.1 on 2022-08-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ListButlers', '0002_alter_list_id_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ListButlers.list'),
            preserve_default=False,
        ),
    ]
